# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: default
  #vmImage: 'ubuntu-latest'

steps:
- task: vsts-habitat-install@3
  displayName: 'Install Habitat'

- task: vsts-habitat-signing-key@3
  inputs:
    habitatOrigin: assurity_tools
  displayName: 'Set Habitat Origin'
    
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: vsts-habitat-build@3
  inputs:
    habitatPlanContext: habitat
    habitatSrcPath: $(Build.SourcesDirectory)
  displayName: 'Habitat Build'
